project:
  type: website
  
website:
  title: Maria Kuruvilla
  navbar:
    left:
      - index.qmd
      - projects.qmd
      - publications.qmd
      - photos.qmd
      - teaching.qmd
      
editor: visual

format:
  html:
    theme: sandstone