project:
  type: website
  
website:
  title: Maria Kuruvilla
  navbar:
    title: false
    left:
      - index.qmd
      - projects.qmd
      - publications.qmd
      - teaching.qmd
      - photos.qmd
    tools:
      - icon: github
        href: https://github.com/maria-kuruvilla
      
editor: visual

format:
  html:
    theme: sandstone